# Generated by Django 4.0.4 on 2022-05-28 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_category_location_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default='location', on_delete=django.db.models.deletion.CASCADE, to='gallery.location'),
        ),
    ]
