# Generated by Django 4.0.4 on 2022-05-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_image_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
