# Generated by Django 4.0.4 on 2022-05-29 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='picture',
            new_name='image',
        ),
    ]
